chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.RoomListView.as_view(), name="index"),
    path('search/', views.SearchResultsView.as_view(), name="search"),
    path('create/', views.ChatRoomCreateView.as_view(), name="create"),
    path('update/<int:pk>/<str:name>/',
         views.ChatRoomUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/<str:name>/',
         views.ChatRoomDeleteView.as_view(), name="delete"),
    path('create/private/<str:second_user>/',
         views.PrivateRoomCreateView.as_view(), name="private"),
    path('chat/<str:room_name>/', views.ChatRoomView.as_view(), name='room'),
]

main_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db.models.signals import m2m_changed
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.core.exceptions import ValidationError

User = get_user_model()


class ChatRoom(models.Model):
    name = models.CharField(max_length=50, unique=True)
    members = models.ManyToManyField(User, related_name='user_rooms')
    logo = models.ImageField(
        upload_to='group_logo/%Y/%m/%d', default="default/group_logo.png")
    is_private = models.BooleanField(default=False)
    owner = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name="first_user")
    second_user = models.ForeignKey(User,
                                    on_delete=models.CASCADE,
                                    related_name="second_user",
                                    null=True,
                                    blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("chat:room", kwargs={"room_name": self.name})

    def clean(self):
        super().clean()
        if self.is_private is True and not self.second_user:
            raise ValidationError('second user not specified')

    def save(self, *args, **kwargs):
        if self.is_private is True:
            if not self.second_user:
                raise ValueError("No second user specified")
        super(ChatRoom, self).save(*args, **kwargs)


class Message(models.Model):
    room = models.ForeignKey(
        ChatRoom, on_delete=models.CASCADE, related_name='room_messages')
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='users_messages')
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(
        upload_to='uploads/%Y/%m/%d', null=True, blank=True)

    def __str__(self):
        return "{}, {}".format(self.id, self.sender.name)


def members_count_changed(sender, **kwargs):
    if kwargs['instance'].is_private is True and kwargs['instance'].members.count() > 2:
        raise ValidationError(
            "You can't assign more than two members to private chat room"
        )


m2m_changed.connect(members_count_changed, sender=ChatRoom.members.through)

chat/forms.py
from django import forms
from django.core import validators
from .models import ChatRoom


class ChatRoomCreateForm(forms.ModelForm):
    name = forms.CharField(min_length=5, validators=[validators.validate_slug])

    class Meta:
        model = ChatRoom
        fields = ('name',)

chat/views.py
import json
from django.shortcuts import render
from django.utils.safestring import mark_safe
from django.contrib.auth import get_user_model
from django.views.generic import View, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from .models import ChatRoom
from .forms import ChatRoomCreateForm
from .mixins import OwnerOnlyMixin

User = get_user_model()


class RoomListView(LoginRequiredMixin, View):
    template_name = 'chat/index.html'

    def get(self, request):
        user = request.user
        room_list = user.user_rooms.all()
        return render(request, self.template_name, {'room_list': room_list})


class ChatRoomView(LoginRequiredMixin, TemplateView):
    template_name = 'chat/room.html'

    def get_context_data(self, **kwargs):
        context = super(ChatRoomView, self).get_context_data(**kwargs)
        context["user"] = mark_safe(json.dumps(self.request.user.name))
        context["room_name"] = mark_safe(json.dumps(kwargs['room_name']))
        context["room_list"] = self.request.user.user_rooms.all()
        context['room_obj'] = ChatRoom.objects.get(name=kwargs['room_name'])
        return context


class SearchResultsView(LoginRequiredMixin, View):
    template_name = 'chat/search_results.html'

    def get(self, *args, **kwargs):
        query = self.request.GET.get('q')
        room_list = ChatRoom.objects.filter(
            name__icontains=query)
        user_list = User.objects.filter(
            name__icontains=query).exclude(pk=self.request.user.pk)
        return render(self.request, self.template_name, {
            'room_list': room_list,
            'user_list': user_list
        })


class ChatRoomCreateView(LoginRequiredMixin, CreateView):
    model = ChatRoom
    form_class = ChatRoomCreateForm
    template_name = 'chat/create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        self.object.members.add(self.request.user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('chat:room', kwargs={
            "room_name": self.object.name})


class PrivateRoomCreateView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        second_user = User.objects.filter(name=kwargs['second_user'])[0]
        private_room, created = ChatRoom.objects.get_or_create(
            is_private=True,
            name=f"{request.user.name}_{second_user.name}",
            owner=request.user,
            second_user=second_user,
        )
        if private_room:
            private_room.members.add(second_user, request.user)
        return HttpResponseRedirect(reverse_lazy(
            'chat:room', kwargs={'room_name': private_room.name}))


class ChatRoomUpdateView(LoginRequiredMixin, OwnerOnlyMixin, UpdateView):
    template_name = 'chat/update.html'
    model = ChatRoom
    form_class = ChatRoomCreateForm

    def get_success_url(self):
        return reverse_lazy('chat:room',
                            kwargs={"room_name": self.object.name})


class ChatRoomDeleteView(LoginRequiredMixin, OwnerOnlyMixin, DeleteView):
    model = ChatRoom
    success_url = reverse_lazy('chat:index')

chat/templates/chat/create.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center mt-4">
        <div class="col-lg-6">
            <h4>Create new Chat</h4>
            <form action="" method="post" class="uniForm">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-outline-secondary" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

chat/templates/chat/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock title %}
{% block content %}

{% comment %} justify-content-center {% endcomment %}
<div class="container-fluid">
    <div class="row mt-4 justify-content-center">
        <div class="col-lg-6">
            <form action="{% url 'chat:search' %}" method="get">
                <div class="input-group mt-3 mb-4 px-0 mx-0">
                    <input class="form-control" id="room-name-input" type="text" name="q" aria-describedby="room-name-submit" placeholder="Search for group or user...">
                    <button class="btn btn-outline-secondary" type="button" id="room-name-submit">Search</button>
                </div>
            </form>
            <div class="mb-4">
                {% for message in messages %}
                    <div class="py-2 alert alert-{{ message.tags }} fade show" role="alert">
                        {{ message }}
                        {% comment %} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button> {% endcomment %}
                    </div>
                {% endfor %}
            </div>
            {% if room_list.count != 0 %}
                {% for room in room_list %}
                    <div class="border row mt-3 mx-0 align-items-center" style="border-radius: 8px;">
                        <div class="col-lg-2">
                            <img class="rounded-circle my-2 img-fluid" src="{{ room.logo.url }}" alt="">
                        </div>
                        <div class="col-lg-10" style="padding-left: 0;">
                            <div class="mt-2">
                                <a style="text-decoration: none;" href="{{ room.get_absolute_url }}">{{ room.name }}</a>
                                {% if room.room_messages.count > 0 %}
                                    <div style="border-bottom: 1px solid grey;"></div>
                                    <p class="mt-2 small" ><span style="color: #222">{{ room.room_messages.last.sender.name }}</span>, {{ room.room_messages.last.text|truncatewords:10 }}...</p>
                                {% else %}
                                    <p class="mt-2"><small style="font-style: italic;">No messages here for now...</small></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            <div class="text-center mt-4">
                <a class="btn btn-secondary" href="{% url 'chat:create' %}">New chat</a>
            </div>
            {% else %}
                <div style="margin-top: 100px;" class="text-center">
                    <h4 class="text-muted" style="font-style: italic;">No chat rooms available at this moment</h4>
                    <a class="btn btn-secondary mt-3" href="{% url 'chat:create' %}">New chat</a>
                </div>
                <div class="text-center mt-5">
                    <img style="max-width: 25%" class="img-fluid" src="{% static 'img/palm1.png' %}" alt="">
                </div>
            {% endif %}
        </div>
    </div>
</div> 

<script>
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {document.querySelector('#room-name-submit').click()}
    };
</script>

{% endblock content %}

chat/templates/chat/room.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Chat Room{% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="row mt-2">
        <div class="col-lg-3" style="overflow-y: auto; height: 600px;">
            <div class="row mx-0">
                <div class="col-lg-12" style="font-size: 35px;">
                    <a href="{% url 'chat:index' %}"><i class="fas fa-arrow-circle-left mb-3" style="color: grey"></i></a>
                </div>
                <div class="border-bottom"></div>
            </div>
            <div class="border row mt-3 mx-0 align-items-center" style="border-radius: 8px;"> 
                <div class="col-lg-3">
                    <img class="rounded-circle my-2 border img-fluid" src="{{ request.user.profile.image.url }}" alt="">
                </div>
                <div class="col-lg-9 px-0">
                    <div class=" mt-2">
                        <p class="mt-0"><a style="text-decoration: none" href="{{ request.user.profile.get_absolute_url }}">{{ request.user.name }}</a><br>{{ request.user.email }}</p>
                    </div>
                </div>
            </div>
            <div class="mt-3" style="border-bottom: 1px solid gray;"></div>
            {% for room in room_list %}
                <div class="border row mt-3 mx-0 align-items-center" style="border-radius: 8px; 
                    {% if room.name == room_name|slice:"1:-1" %}
                        background-color: #00FFFF
                    {% endif %}">
                    <div class="col-lg-3">
                        <img class="rounded-circle img-fluid border" src="{{ room.logo.url }}" alt="">
                    </div>
                    <div class="col-lg-9" style="padding-left: 0;">
                        <div class="mt-2">
                            <a style="text-decoration: none;" href="{{ room.get_absolute_url }}">{{ room.name }}</a>
                            <div class="border-bottom"></div>
                            {% if room.room_messages.count != 0 %}
                                <p class="mt-2 small" >
                                    <span style="color: #222">
                                        {{ room.room_messages.last.sender.name }},</span>
                                        {{ room.room_messages.last.text|truncatewords:5 }}...
                                </p>
                            {% else %}
                                <p class="mt-2"><small style="font-style: italic;">No messages here for now...</small></p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-lg-6">
            <div id="chat-log" style="overflow-y: auto; height: 570px;"></div>
            <div class="input-group my-3">
                <input class="form-control" id="chat-message-input" type="text" aria-describedby="chat-message-submit">
                <button class="btn btn-outline-secondary" type="button" onclick="getFile()" id="file-input">File</button>
                <button class="btn btn-outline-secondary" type="button" id="chat-message-submit">Send</button>
            </div>
            <input id="file-form" type="file" hidden>
        </div>
        <div class="col-lg-3" style="overflow-y: auto; height: 600px;">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="text-center">
                        <img style="max-height: 200px;" class="rounded-circle img-fluid border" src="{{ room_obj.logo.url }}" alt="">
                    </div>
                    <div class="mt-4">
                        <ul class="list-unstyled my-0 py-0" style="font-size: 14px;">
                            <li><p>Owner: {{ room_obj.owner.name|capfirst }}</p></li>
                            <li><p>Created at: {{ room_obj.created }}</p></li>
                            <li><p>Members: {{ room_obj.members.count }}</p></li>
                            <li><p>Messages: {{ room_obj.room_messages.count }}</p></li>
                            {% if room_obj.owner == request.user %}
                                <a style="width: 100%" class="btn btn-secondary mb-3" href="{% url 'chat:update' room_obj.id room_obj.name %}">Update</a>
                                <form action="{% url 'chat:delete' room_obj.id room_obj.name %}" method="POST"
                                    onsubmit="return confirm('Do you really want to delete this chat?');">
                                    {% csrf_token %}
                                    <button style="width: 100%" class="btn btn-outline-secondary" type="submit">Delete</button>
                                </form>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/reconnecting-websocket.js' %}"></script>
{% comment %} <script src="{% static 'js/imageUpload.js' %}"></script> {% endcomment %}
<script src="{% static 'js/chunk.js' %}"></script>
<script>

    const roomName = {{ room_name }};
    const user = {{ user }};
    const chatLog = document.querySelector('#chat-log');
    const messageInputDom = document.querySelector('#chat-message-input');
    const messageSubmit = document.querySelector('#chat-message-submit');
    const chatSocket = new ReconnectingWebSocket(
        'ws://' + window.location.host + '/ws/chat/' + roomName + '/'
    );

// ================== websocket staff =======================

    chatSocket.onopen = function(e) {
        fetchMessages();
    };

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const option = data['option']

        if (option === 'new_message') {
            createMessage(data['message']);
        } else if (option === 'fetch' && chatLog.querySelectorAll('div').length < 1) {
            for (let i=0; i<data['messages'].length; i++) {
                createMessage(data['messages'][i]);
            }
        } else if (option === 'image') {
            createMessage(data['value'])  
        // ======== chunk proccessing =============
        } else if (option === 'dispatch') {
            dispatch(data)
        }
        chatLog.scrollTop = chatLog.scrollHeight;
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

// ==================================================
//=================================================== img processing

let dispatch = function (data) {
    console.log(data.action)
    switch (data.action) {
        case 'ready':
            loadFile(0);
            console.log(data.action)
            break;
        case 'progress':
            loadFile(data.file_size);
            break;
        case 'complete':
            break;
    }
}

// ============= load previous messages ===================

    function fetchMessages() {
        chatSocket.send(JSON.stringify({'option': 'fetch'}));
    };

// ============ send text message =====================

    messageInputDom.focus();
    messageInputDom.onkeyup = function(e) {
        if (e.keyCode === 13) {
            messageSubmit.click();
        }
    };

    messageSubmit.onclick = function(e) {
        const message = messageInputDom.value;
        if (message.length > 0) {
            chatSocket.send(JSON.stringify({
                'option': 'new_message',
                'message': message,
                'user': user
            }));
            messageInputDom.value = '';
        }
    };

// ================ render new message ==================

    function createMessage(data) {
        let msg = document.createElement('div');
        let msgPTag = document.createElement('p');
        let msgSpan = document.createElement('span');
        msg.style = 'margin-top: 20px';
        msgPTag.textContent = data.text;
        if (data.sender === user) {
            msg.className = 'text-right';
        } else {
            msg.className = 'text-left';   
        }
        msgSpan.textContent = '[' + data.sender + ' at ' + data.timestamp + ']';
        msg.appendChild(msgSpan)
        msg.appendChild(msgPTag)
        if (data.image != undefined){
            let msgImg = document.createElement('img');
            msgImg.className = 'image';
            msgImg.src = 'data:image/jpeg;base64,' + data.image.slice(2,-1);
            msg.appendChild(msgImg);
        }
        chatLog.appendChild(msg);
    };

</script>
{% endblock content %}

chat/templates/chat/search_results.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row mt-4 justify-content-center">
        <div class="col-lg-6">
            <form action="{% url 'chat:search' %}" method="get">
                <div class="input-group mt-3 mb-5 px-0 mx-0">
                    <input class="form-control" id="room-name-input" type="text" name="q" aria-describedby="room-name-submit">
                    <button class="btn btn-outline-secondary" type="button" id="room-name-submit">Send</button>
                </div>
            </form>
            {% if room_list.count != 0 or user_list.count != 0 %}
                {% if room_list.count != 0 %}
                    <h4>Public groups:</h4>
                    {% for room in room_list %}
                        <div class="border row mt-3 mx-0 align-items-center" style="border-radius: 8px;">
                            <div class="col-lg-2">
                                <img class="rounded-circle border my-2 img-fluid" src="{{ room.logo.url }}" alt="">
                            </div>
                            <div class="col-lg-10" style="padding-left: 0;">
                                <div class="mt-2">
                                    <a style="text-decoration: none;" href="{{ room.get_absolute_url }}">{{ room.name }}</a>
                                    <div style="border-bottom: 1px solid grey"></div>
                                    {% if room.room_messages.count != 0 %}
                                        <p class="mt-2 small" >
                                            <span style="color: #222">
                                                {{ room.room_messages.last.sender.name }},</span>
                                                {{ room.room_messages.last.text|truncatewords:5 }}...
                                        </p>
                                    {% else %}
                                        <p class="mt-2"><small style="font-style: italic;">No messages here for now...</small></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                {% if user_list.count != 0 %}
                    <h4 class="mt-5">Available users:</h4>
                    {% for user in user_list %}
                        <div class="border row mx-0 mt-3 align-items-center" style="border-radius: 8px;"> 
                            <div class="col-lg-2">
                                <img class="rounded-circle my-2 border img-fluid" src="{{ user.profile.image.url }}" alt="">
                            </div>
                            <div class="col-lg-10 px-0">
                                <div class="mt-0 pt-0">
                                    <p style="line-height: 16px;"><strong>{{ user.name }}</strong> <br>{{ user.email }}</p>
                                    <form action="{% url 'chat:private' user.name %}" method="POST">
                                        {% csrf_token %}
                                        <button class=" me-auto btn btn-success py-0" type="submit">send msg</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="text-center mt-4">
                    <a class="btn btn-outline-secondary" href="{% url 'chat:index' %}">Go back</a>
                    <a class="btn btn-secondary" href="{% url 'chat:create' %}">New chat</a>
                </div>
            {% else %}
                <div class="text-center">
                    <h4 >We cant find no groups or users</h4>
                    <img class="mt-4" style="max-width: 15%" class="img-responsive" src="{% static 'img/sad_smile.png' %}" alt="">
                </div>
                <div class="text-center mt-4">
                    <a class="btn btn-outline-secondary" href="{% url 'chat:index' %}">Go back</a>
                    <a class="btn btn-secondary" href="{% url 'chat:create' %}">New chat</a>
                </div>            
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

chat/templates/chat/update.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center mt-4">
        <div class="col-lg-6">
            <h4>Update new Chat</h4>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-outline-secondary" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}