chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.RoomListView.as_view(), name="index"),
    path('search/', views.SearchResultsView.as_view(), name="search"),
    path('create/', views.ChatRoomCreateView.as_view(), name="create"),
    path('update/<int:pk>/<str:name>/',
         views.ChatRoomUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/<str:name>/',
         views.ChatRoomDeleteView.as_view(), name="delete"),
    path('create/private/<str:second_user>/',
         views.PrivateRoomCreateView.as_view(), name="private"),
    path('chat/<str:room_name>/', views.ChatRoomView.as_view(), name='room'),
]

main_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView, ActivationView, ProfileView
from django.views.generic import TemplateView


app_name = 'users'
urlpatterns = [
    path('registration/', SignUpView.as_view(), name='registration'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logout.html'), name="logout"),
    path('waiting-for-activation/', TemplateView.as_view(
        template_name="users/activation/wait.html"),
        name="waiting_for_activation"),
    path('activation-fialed/', TemplateView.as_view(
        template_name="users/activation/fail.html"),
        name="activation_failed"),
    path('activate/<uidb64>/<token>/',
         ActivationView.as_view(), name='activate'),
    path('profile/<int:pk>/', ProfileView.as_view(), name="profile"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils import timezone
from .managers import CustomUserManager
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('email address', unique=True)
    name = models.CharField('username', max_length=30, unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', ]

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to="uploads/profile_images/%Y/%m/%d",
        default='default/profile.jpg')

    class Meta:
        verbose_name_plural = 'Profile'

    def __str__(self):
        return str(self.user.name)

    def get_absolute_url(self):
        return reverse('users:profile', kwargs={'pk': self.user.pk})


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_update_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email', 'name')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, View
from django.urls import reverse_lazy
from django.core.mail import EmailMessage
from django.contrib.auth import get_user_model, login
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CustomUserCreationForm
from .tokens import account_activation_token
from .models import Profile

User = get_user_model()


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:waiting_for_activation')
    template_name = 'users/registration.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        current_site = get_current_site(self.request)
        mail_subject = 'Activate your account.'
        message = render_to_string('users/activation/message.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(
            mail_subject, message, to=[to_email]
        )
        email.send()
        return super().form_valid(form)


class ActivationView(View):
    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist) as e:
            user = None
            print(e)
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('chat:index')
        else:
            return redirect('users:activation_failed')


class ProfileView(LoginRequiredMixin, View):
    login_url = 'users:login'

    def get(self, request, *args, **kwargs):
        user = User.objects.get(id=request.user.pk)
        profile = Profile.objects.get(user=user)

        return render(request, 'users/profile.html', {
            'user': user,
            'profile': profile})

users/templates/users/activation/fail.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h3>Not valid credentials, check your email another one time and retry</h3>
            </div>
        </div>
    </div>
    
{% endblock content %}

users/templates/users/activation/message.html
{% autoescape off %}  
Hi {{ user.pseudonym }},  
Please click on the link below to confirm your registration,
*** This link available only for 5 minutes ***

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}  

If you think, it's not you, then just ignore this email.  
{% endautoescape %}

users/templates/users/activation/wait.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <h3>Check your email, for activation message.</h3>
            <h4 style="color: red;">Link available only 10 minutes</h4>
        </div>
    </div>
</div>
<div><span class="cycleTimerBox"><canvas height="200" width="200" id="cycleTimer"/></span></div>

<style>
    .cycleTimerBox {
        display: inline-block;
        width:200px;
        height: 200px;
        border-radius: 50%;
        background-color: #fff;
        float: left;
    }
</style>

<script>

    function createTimer(time) {
        var counter = document.getElementById('cycleTimer').getContext('2d');
        var no = time;
        var pointToFill = 4.72;
        var cw = counter.canvas.width;
        var ch = counter.canvas.height;
        var diff;

        function fillCounter() {
            diff = ((no / time) * Math.PI * 2 * 10);
            counter.clearRect(0, 0, cw, ch);
            counter.lineWidth = 4;
            counter.fillStyle = '#000';
            counter.strokeStyle = '#F5E0A9';
            counter.textAlign = 'center';
            counter.font = "25px monospace";
            counter.fillText(no + 'sec', 100, 110);
            counter.beginPath();
            counter.arc(110, 110, 70, pointToFill, diff / 10 + pointToFill);
            counter.stroke();
            if (no == 0) {
                clearTimeout(fill);
            }
            no--;
        } var fill = setInterval(fillCounter, 1000);
    } createTimer(560);
    
</script>

{% endblock content %}